### ISSUE TITLE
License

### ISSUE THREAD

**Issue by edwellbrook** [samueltangz/swift-noise-protocol#12]
Hey @samueltangz!

Thanks for publishing this library. It's a great start and I'd love to help contribute and send some PRs with updates.

To do this, could you please decide a license and add a LICENSE file to the project? (My preference is MIT, though anything permissive like Apache 2 (e.g. [apple/swift](https://github.com/apple/swift/blob/ae2a4cca1492bb4e966a652281ce7f86a478dc49/LICENSE.txt) would work too).

Once that's done I'd love to share some contributions to the project.

Thank you!

Ed

**Comment by samueltangz** [comment]
We will be using MIT license since now (via #13)! I'll be creating some issues to make it feature-complete. Thanks! :)
